import { HistoryItem } from '@/types/index.ts';

export const mockHistoryList: HistoryItem[] = [
  {
    id: 'SC-001',
    title: '회원가입 시나리오',
    description: '신규 사용자 회원가입 후 로그인까지 확인',
    executedAt: '2025-04-23T14:15:00+09:00',
    totalDurationMs: 550,
    averageDurationMs: 275,
    filePath: '/local/result/user',
    baseUrl: 'http://loacalhost:8080',
    isScenarioSuccess: false,
    results: [
      {
        endpoint: '/api/signup',
        method: 'POST',
        requestBody: { email: 'test@test.com', password: '1234' },
        requestHeader: { Authorization: 'Bearer abc.def.ghi', contentType: 'application/json' },
        responseBody: { status: 'success' },
        responseHeaders: { contentType: 'application/json' },
        statusCode: 200,
        startTime: '2025-04-23T14:15:01.000+09:00',
        endTime: '2025-04-23T14:15:01.300+09:00',
        durationMs: 300,
        isRequestSuccess: true,
      },
      {
        endpoint: '/api/login',
        method: 'POST',
        requestBody: { email: 'test@test.com', password: '1234' },
        requestHeaders: {
          Authorization: 'Bearer abc.def.ghi',
          'Content-Type': 'application/json',
        },
        responseBody: { token: 'abc.def.ghi' },
        responseHeaders: { contentType: 'application/json' },
        statusCode: 404,
        startTime: '2025-04-23T14:15:02.000+09:00',
        endTime: '2025-04-23T14:15:02.250+09:00',
        durationMs: 250,
        isRequestSuccess: false,
      },
    ],
  },
  {
    id: 'SC-002',
    title: '시나리오2',
    description: '신규??? 사용자 회원가입 후 로그인까지 확인',
    executedAt: '2025-04-23T14:15:00+09:00',
    totalDurationMs: 550,
    averageDurationMs: 275,
    filePath: '/local/result/user',
    baseUrl: 'http://loacalhost:8080',
    isScenarioSuccess: false,
    results: [
      {
        endpoint: '/api/signup',
        method: 'POST',
        requestBody: { email: 'test@test.com', password: '1234' },
        requestHeader: { Authorization: 'Bearer abc.def.ghi', contentType: 'application/json' },
        responseBody: { status: 'success' },
        responseHeaders: { contentType: 'application/json' },
        statusCode: 200,
        startTime: '2025-04-23T14:15:01.000+09:00',
        endTime: '2025-04-23T14:15:01.300+09:00',
        durationMs: 300,
        isRequestSuccess: true,
      },
      {
        endpoint: '/api/login',
        method: 'POST',
        requestBody: { email: 'test@test.com', password: '1234' },
        requestHeaders: {
          Authorization: 'Bearer abc.def.ghi',
          'Content-Type': 'application/json',
        },
        responseBody: { token: 'abc.def.ghi' },
        responseHeaders: { contentType: 'application/json' },
        statusCode: 404,
        startTime: '2025-04-23T14:15:02.000+09:00',
        endTime: '2025-04-23T14:15:02.250+09:00',
        durationMs: 250,
        isRequestSuccess: false,
      },
    ],
  },
];
